/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package iteratorizer

class App(val lists: List<List<Int>>) {
  private val itX: List<Iterator<Int>> by lazy {
    lists.map {it.iterator()}
  }
 
  private val current: MutableList<Int> by lazy {
    itX.mapTo(mutableListOf()) {it.next()}
  }
 
  private val inf = Int.MAX_VALUE
  private val size = lists.size
  private var count = lists.sumBy {it.size}
  private var idx = 0

  fun getNext() {
    if (current[idx] == current.min()/* && hasNext()*/) {
      println("${current[idx]}\t$current")
      current[idx] = if (itX[idx].hasNext()) itX[idx].next() else inf
      count --
    }
    idx = if (idx == size - 1) 0 else idx + 1
  }

  fun hasNext() = count > 0
}

fun main(args: Array<String>) {
  val app = App(listOf(
    listOf(1, 8, 12, 17, 26, 31),
    listOf(2, 7, 35, 40),
    listOf(10, 13, 15, 18)
  ))
  while (app.hasNext()) app.getNext()
}

// vim: se et ts=2 sw=2 number:
