/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package iteratorizer

class App {
  val lists = listOf(
    listOf(1, 8, 12, 17, 26, 31),
    listOf(2, 7, 35, 40),
    listOf(10, 13, 15, 18)
  )
}

fun main(args: Array<String>) {
  val app = App()
  val itX = listOf(
    app.lists[0].iterator(),
    app.lists[1].iterator(),
    app.lists[2].iterator()
  )
  val current = mutableListOf(itX[0].next(), itX[1].next(), itX[2].next())
  var count = app.lists[0].size + app.lists[1].size + app.lists[2].size
  val inf = Int.MAX_VALUE
  while (count > 0) {
    for (i in 0 .. 2) {
      if (current[i] == current.min()) {
        println("${current[i]}\t$current")
        current[i] = if (itX[i].hasNext()) itX[i].next() else inf
        if ((count --) == 1) break
      }
    }
  }
}

// vim: se et ts=2 sw=2 number:
